version: "3"
services:
    db:
        image: mysql:5.7
        command: --max-allowed-packet=67108864 --init-file /dump.sql
        ports:
            - "3316:3306"
        volumes:
            - /var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
            - ./dump.sql:/dump.sql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=relearning
    php:
        build: ./
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        links:
            - "db"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - "db"
        ports:
            - "8002:80"
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
